### PR TITLE
ansible: iscsi: modify the regex for iscsi ip validating

### PR DESCRIPTION
**Pull request by kenzhaoyihui**
Could someone help to check this patch? Thanks in advance!

### CODE REVIEW

**Comment by mykaul** [comment]
This is a read-only mirror of the repo that we store @ gerrit.ovirt.org - can you paste the patch there?
Also, please explain the motivation for the regexp change.
cc @tiraboschi

**Comment by kenzhaoyihui** [comment]
`_IPADDR_RE = re.compile(r'^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$')`， this regex will match a valid ip address, and don't avoid to use the 
```
 for a in address.split(','):
            match = self._IPADDR_RE.match(a)
            if match:
                # TODO: figure out a better regexp
                # avoiding this check
                valid &= True
                for i in match.groups():
                    valid &= int(i) >= 0
                    valid &= int(i) < 255
```

**Comment by xilazz** [comment]
Hello, I want to ask if using hosted-engine --deploy will be supported at present when the underlying bond6 schema interface is used?

**Comment by sandrobonazzola** [comment]
Please ask questions on users@ovirt.org mailing list

**Pull request closed without merging**
