### PR TITLE
Use ansible-core-2.12

### PR DESCRIPTION
**Pull request by mwperina**
Bug-Url: https://bugzilla.redhat.com/2065196
Signed-off-by: Martin Perina <mperina@redhat.com>

### CODE REVIEW

**Comment by mwperina** [comment]
Asaf, could you please take over and verify this change? It can be done independently on engine.
Thanks!

**Comment by arachmani** [comment]
> Asaf, could you please take over and verify this change? It can be done independently on engine. Thanks!

I've already started to check it using https://github.com/oVirt/ovirt-hosted-engine-setup/pull/23,
which requires also https://github.com/oVirt/cockpit-ovirt/pull/20

**Comment by sandrobonazzola** [comment]
> I thought we have already dropped support for cockpit related installation. Or am I missing something?

it's deprecated and cockpit-ovirt is unmaintained but not dropped from the system yet as it still works and used by RHHI.

**Pull request closed without merging**
