### PR TITLE
plugins: Enhance DC/cluster input on restore

### PR DESCRIPTION
**Pull request by didib**
- Do not supply a default

- Clarify the importance of providing accurate input

TODO: Perhaps add to the message, instructions of how to check the
DC/cluster in the DB dump.

Bug-Url: https://bugzilla.redhat.com/1881280
Change-Id: I63e526b253aac3771034aac23b8a9f1d787156be
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

### CODE REVIEW

**Comment by didib** [comment]
Verified locally:

with a backup:
```
          Please enter the name of the data center where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target data center you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Data center:
[ ERROR ] Please specify value

          Please enter the name of the data center where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target data center you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Data center: Default

          Please enter the name of the cluster where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target cluster you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Cluster:
[ ERROR ] Please specify value

          Please enter the name of the cluster where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target cluster you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Cluster: Default
```

Without backup:
```
          Please enter the name of the data center where you want to deploy this hosted-engine host.
          Data center [Default]: 
         
          Please enter the name of the cluster where you want to deploy this hosted-engine host.
          Cluster [Default]: 
```

**Review by germanovm — APPROVED** [review]
Thank you for the change, makes it much clearer to the user that a correct value must be supplied otherwise problems can occur.

**Comment by didib** [comment]
> 
> TODO: Perhaps add to the message, instructions of how to check the DC/cluster in the DB dump.

Gave up on this for now.

**Comment by didib** [comment]
Added a line about creating a new dc/cluster. verified:
```
          Please enter the name of the data center where you want to deploy this hosted-engine host.
          Please note:   
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target data center you wish to add the HostedEngine VM and this host to.
          You might also supply a new value - in this case, the data center will be created automatically. This can be useful for moving an existing hosted-engine setup to new storage.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Data center: Default
                                                                                     
          Please enter the name of the cluster where you want to deploy this hosted-engine host.
          Please note:                                                          
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target cluster you wish to add the HostedEngine VM and this host to.
          You might also supply a new value - in this case, the cluster will be created automatically. This can be useful for moving an existing hosted-engine setup to new storage.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Cluster:            
```

**Comment by germanovm** [comment]
"You might also supply a new value - in this case, the cluster will be created automatically. This can be useful for moving an existing hosted-engine setup to new storage."

In 99% of the time, the new Storage is attached to the existing DC and just replaces some old SAN (VM disks have all been moved via Admin Portal and only remaining is HE), so I think we should remove that part.

I'd add it to the first one, like this:

If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts.  This can be useful for moving an existing hosted-engine setup to new storage which will be attached to the existing Data-Center of Hosted-Engine.

**Comment by didib** [comment]
Took your text almost as-is (other than {what} and capitalization etc.).

However, I admit that the longer we work on this, the more it seems to me like it's simply impossible to squeeze into a short text all the information relevant to the user at this point...

**Comment by didib** [comment]
Anyway, verified. Let's merge this quickly and forget about it, or replace with a link to somewhere with considerably more text...
```
          Please enter the name of the data center where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts. This can be useful for moving an existing hosted-engine setup to new storage which will be attached to the existing data center of HostedEngine.
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target data center you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Data center: 
[ ERROR ] Please specify value
         
          Please enter the name of the data center where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts. This can be useful for moving an existing hosted-engine setup to new storage which will be attached to the existing data center of HostedEngine.
          If you are restoring a backup of a hosted-engine, this value should be the data center of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target data center you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Data center: a1
         
          Please enter the name of the cluster where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts. This can be useful for moving an existing hosted-engine setup to new storage which will be attached to the existing cluster of HostedEngine.
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target cluster you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Cluster: 
[ ERROR ] Please specify value
         
          Please enter the name of the cluster where you want to deploy this hosted-engine host.
          Please note:
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts. This can be useful for moving an existing hosted-engine setup to new storage which will be attached to the existing cluster of HostedEngine.
          If you are restoring a backup of a hosted-engine, this value should be the cluster of the HostedEngine VM and hosts.
          If you are migrating from a standalone engine to a hosted-engine, this value should be the target cluster you wish to add the HostedEngine VM and this host to.
          The default, for new deployments, is "Default", but is not supplied here, because you are restoring from a backup - please make sure that the value you supply is correct.
          Cluster: a2
```

**Comment by michalskrivanek** [comment]
lgtm

**Comment by didib** [comment]
Ran he-basic manually with https://github.com/oVirt/ovirt-engine/pull/405 (before it was merged) and it passed:

https://redir.apps.ovirt.org/dj/job/ds-ost-baremetal_manual/38942/

**Review by arachmani — APPROVED** [review]
LGTM

**Pull request merged**
